# Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/dev
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/realms/dev/protocol/openid-connect/certs
