name: Run tests & checks for PRs on main

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run detekt with Gradle
        if: success() || failure()
        run: ./gradlew detekt
      - name: Upload detekt results
        uses: github/codeql-action/upload-sarif@v1
        if: success() || failure()
        with:
         sarif_file: build/reports/detekt/detekt.sarif
      - name: Build & test with Gradle
        run: ./gradlew test
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        if: success() || failure()
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
